[mgr]
linemode = "size"

[opener]
view = [
    { run = 'imvs "$@"', for = "unix" },
]
listen = [
    { run = 'mpa "$@"', for = "unix" },
]
viewpdf = [
    { run = 'zathura "$@"', desc = "Zathura", for = "unix" },
]
term = [
    { run = 'hyprctl dispatch exec -- foot -D "$1"', desc = "Terminal", for = "unix" },
]
[open]
rules = [
  # Folder
  { name = "*/", use = [ "edit", "term", "open", "reveal" ] },
  # Text
  { mime = "text/*", use = [ "edit", "reveal" ] },
  # Image
  { mime = "image/*", use = [ "view", "open", "reveal" ] },
  # Video
  { mime = "video/*", use = [ "play", "reveal" ] },
  # Audio
  { mime = "audio/*", use = [ "listen", "reveal" ] },
  # Archive
  { name = "*.{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = [ "extract", "reveal" ] },
  # JSON
  { mime = "application/{json,ndjson}", use = [ "edit", "reveal" ] },
  { mime = "application/pdf", use = [ "viewpdf", "open", "reveal" ] },
  { mime = "*/javascript", use = [ "edit", "reveal" ] },
  # Empty file
  { mime = "inode/empty", use = [ "edit", "reveal" ] },
  # Fallback
  { name = "*", use = [ "open", "reveal" ] },
]
[plugin]
prepend_previewers = [
  # Archive previewer
  { mime = "application/*zip",            run = "ouch" },
  { mime = "application/x-tar",           run = "ouch" },
  { mime = "application/x-bzip2",         run = "ouch" },
  { mime = "application/x-7z-compressed", run = "ouch" },
  { mime = "application/x-rar",           run = "ouch" },
  { mime = "application/x-xz",            run = "ouch" },
  { mime = "application/xz",              run = "ouch" },
]
