const layout = [
  [
    { label: "`", shiftLabel: "~", code: 41},
    { label: "1", shiftLabel: "!", code: 2},
    { label: "2", shiftLabel: "@", code: 3},
    { label: "3", shiftLabel: "#", code: 4},
    { label: "4", shiftLabel: "$", code: 5},
    { label: "5", shiftLabel: "%", code: 6},
    { label: "6", shiftLabel: "^", code: 7},
    { label: "7", shiftLabel: "&", code: 8},
    { label: "8", shiftLabel: "*", code: 9},
    { label: "9", shiftLabel: "(", code: 10},
    { label: "0", shiftLabel: ")", code: 11},
    { label: "-", shiftLabel: "_", code: 12},
    { label: "=", shiftLabel: "+", code: 13},
    { label: "Backspace", width: 6, code: 14},
    { label: "Del", code: 111},
  ],
  [
    { label: "Tab", width: 14, code: 15},
    { label: "q", shiftLabel: "Q", code: 16},
    { label: "w", shiftLabel: "W", code: 17},
    { label: "e", shiftLabel: "E", code: 18},
    { label: "r", shiftLabel: "R", code: 19},
    { label: "t", shiftLabel: "T", code: 20},
    { label: "y", shiftLabel: "Y", code: 21},
    { label: "u", shiftLabel: "U", code: 22},
    { label: "i", shiftLabel: "I", code: 23},
    { label: "o", shiftLabel: "O", code: 24},
    { label: "p", shiftLabel: "P", code: 25},
    { label: "[", shiftLabel: "{", code: 26},
    { label: "]", shiftLabel: "}", code: 27},
    { label: "\\", shiftLabel: "|", code: 43, width: 14},
    { label: "pgUp", code: 16},
  ],
  [
    { label: "Esc", code: 1, width: 10},
    { label: "a", shiftLabel: "A", code: 30},
    { label: "s", shiftLabel: "S", code: 31},
    { label: "d", shiftLabel: "D", code: 32},
    { label: "f", shiftLabel: "F", code: 33},
    { label: "f", shiftLabel: "G", code: 34},
    { label: "h", shiftLabel: "H", code: 35},
    { label: "j", shiftLabel: "J", code: 36},
    { label: "k", shiftLabel: "K", code: 37},
    { label: "l", shiftLabel: "L", code: 38},
    { label: ";", shiftLabel: ":", code: 39},
    { label: "'", shiftLabel: "\"", code: 40},
    { label: "Enter", code: 28, width: 8},
    { label: "pgDn", code: 16},
  ],
  [
    { label: "shift", code: 42, width: 8},
    { label: "z", shiftLabel: "Z", code: 44},
    { label: "x", shiftLabel: "X", code: 45},
    { label: "c", shiftLabel: "C", code: 46},
    { label: "v", shiftLabel: "V", code: 47},
    { label: "b", shiftLabel: "B", code: 48},
    { label: "n", shiftLabel: "N", code: 49},
    { label: "m", shiftLabel: "M", code: 50},
    { label: ",", shiftLabel: "<", code: 51},
    { label: ".", shiftLabel: ">", code: 52},
    { label: "/", shiftLabel: "?", code: 53},
    { label: "shift", code: 54, width: 8},
    { label: "^", code: 53},
    { label: "end", code: 16},
  ],
  [
    { label: "ctrl", code: 29, width: 13},
    { label: "meta", code: 125, width: 13},
    { label: "alt", code: 56, width: 13},
    { label: "space", code: 57, width: 2},
    { label: "Lv3", code: 97, width: 13},
    { label: "<", code: 16},
    { label: "v", code: 16},
    { label: ">", code: 16},
  ]
];
